apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: datalens
spec:
  parentRefs:
    - name: yt-demo
      namespace: default
      sectionName: ytsaurus
  hostnames:
    - "datalens-{{namespace}}.demo.ytsaurus.tech"
  rules:
    - backendRefs:
        - name: datalens-ui-lb
          port: 80
