apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-compeng
  labels:
    name: pg-compeng
spec:
  replicas: 1
  serviceName: pg-compeng-headless
  selector:
    matchLabels:
      name: pg-compeng
  template:
    metadata:
      labels:
        name: pg-compeng
    spec:
      containers:
        - name: pg-compeng
          image: cr.yandex/crpgg53svilvkn982otu/postgres:13-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          resources:
            requests:
              cpu: 250m
              memory: 2G
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql

      restartPolicy: Always
      
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "yc-network-ssd"
      resources:
        requests:
          storage: 1Gi
