apiVersion: v1
kind: ConfigMap
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: YT prometheus datasource
        type: prometheus
        url: http://prometheus.{{namespace}}.svc.cluster.local:9090
        uid: YT-prometheus
        access: proxy
        basicAuth: true
        basicAuthUser: admin
        jsonData:
          httpMethod: POST
        secureJsonData:
          basicAuthPassword: '{{password}}'
        editable: false
  dashboards-conf.yaml: |-
    apiVersion: 1
    providers:
      - name: 'YT dashboard provider'
        # <string> name of the dashboard folder.
        folder: 'Ytsaurus'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
metadata:
  name: grafana
