apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: yt-demo
      namespace: default
      sectionName: ytsaurus
  hostnames:
    - "grafana-{{ namespace }}.demo.ytsaurus.tech"
  rules:
    - backendRefs:
        - name: grafana
          port: 3000

