apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: jupyter
spec:
  parentRefs:
    - name: yt-demo
      namespace: default
      sectionName: ytsaurus
  hostnames:
    - "jupyter-{{ namespace }}.demo.ytsaurus.tech"
  rules:
    - backendRefs:
        - name: jupyterlab
          port: 80

