apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: prometheus
spec:
  parentRefs:
    - name: yt-demo
      namespace: default
      sectionName: ytsaurus
  hostnames:
    - "prometheus-{{ namespace }}.demo.ytsaurus.tech"
  rules:
    - backendRefs:
        - name: prometheus
          port: 9090

