apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: ui
spec:
  parentRefs:
    - name: yt-demo
      namespace: default
      sectionName: ytsaurus
  hostnames:
    - "yt-{{ namespace }}.demo.ytsaurus.tech"
  rules:
    - backendRefs:
        - name: ytsaurus-ui
          port: 80

